services:
  - type: web
    name: auto-pdde
    env: docker
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: '3.11' # Garante a versão do Python
      - key: PYTHONUNBUFFERED # Recomendado para logs em contêineres
        value: 'True'
